os: linux
matrix:
  include:
    - language: dart
      dart: stable
      stage: Flutter Mobile Application Test
      before_install:
        - "cd dengue_app"
      addons:
        apt:
          packages:
            - lib32stdc++6
      install:
        - git clone https://github.com/flutter/flutter.git -b stable
        - ./flutter/bin/flutter doctor
      script:
        - ./flutter/bin/flutter test
      cache:
        directories:
          - $HOME/.pub-cache

    - language: python
      python:
        - "3.7"
      stage: Flask API Test
      before_install:
        - "cd backend"
      install:
        - pip install -r requirements.txt
      script:
        - pytest
